tag_prefix = ""
from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = []
post_bump_hooks = [
    "git push --no-verify",
    "git push origin {{version}} --no-verify",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "terraform-neptune"
owner = "EKGF"
authors = [
    { username = "jgeluk", signature = "Jacobus Geluk" },
]

[bump_profiles]

[packages]
